AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Very simple REST-API for AWS Lambda

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.get
      Runtime: python3.6
      CodeUri: s3://io-zenetics-lambda-test/lambda-reast-sample-api.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{name}
            Method: get
